# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2018 - 2021 Gemeente Amsterdam
# Generated by Django 2.1.2 on 2019-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0030_merge_20190124_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.CharField(blank=True, choices=[
                ('m', 'Reported'),
                ('i', 'Awaiting handling'),
                ('b', 'In progress'),
                ('h', 'On hold'),
                ('ready to send', 'To send naar extern systeem'),
                ('o', 'Completed'),
                ('a', 'Cancelled'),
                ('reopened', 'Reopened'),
                ('s', 'Split'),
                ('sent', 'Verzonden naar extern systeem'),
                ('send failed', 'Verzending naar extern systeem mislukt'),
                ('done external', 'Melding is afgehandeld in extern systeem')
            ], default='m', help_text='Melding status', max_length=20),
        ),
    ]
