# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2019 - 2021 Gemeente Amsterdam
# Generated by Django 2.1.7 on 2019-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0044_auto_20190418_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignment',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
