# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.13 on 2022-06-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0159_location_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.PositiveBigIntegerField(editable=False)),
                ('signal_uuid', models.UUIDField(editable=False)),
                ('parent_signal_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('signal_state', models.CharField(blank=True, choices=[
                    ('m', 'Reported'),
                    ('i', 'Awaiting handling'),
                    ('b', 'In progress'),
                    ('h', 'On hold'),
                    ('planned', 'Planned'),
                    ('ready to send', 'External: to send'),
                    ('o', 'Completed'),
                    ('a', 'Cancelled'),
                    ('reopened', 'Reopened'),
                    ('s', 'Split'),
                    ('closure requested', 'External: closure requested'),
                    ('reaction requested', 'Reaction requested'),
                    ('reaction received', 'Reaction received'),
                    ('sent', 'External: sent'),
                    ('send failed', 'External: failed'),
                    ('done external', 'External: completed'),
                    ('reopen requested', 'Request to reopen')
                ], editable=False, max_length=20)),
                ('signal_state_set_at', models.DateTimeField(editable=False)),
                ('signal_created_at', models.DateTimeField(editable=False)),
                ('deleted_by', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('batch_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('action', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')],
                                            editable=False, max_length=12)),
                ('note', models.TextField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                               related_name='+', to='signals.category')),
            ],
        ),
    ]
